'use strict';

/*
 * try/catch
 * Ошибки фазы парсинга обработать нельзя. Только ошибки фазы выполнения.
 * Объект ошибки
 * try/catch работает только с синхронным кодом
 * Обработка ошибок в асинхронном коде
 */

// console.log('Start!');

// setTimeout(() => {
//   try {
//     const a = 5;
//     console.log(a.join());
//   } catch (err) {
//     console.log(err);
//   }
// }, 1000);

// console.log('End!');
